version: "3.8"

services:
  front:
    build:
      context: ./.docker/front
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./front:/app:cached
    stdin_open: true
    tty: true
    depends_on:
      - nginx
  nginx:
    container_name: nginx
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./api:/app:cached
    tty: true
    depends_on:
      - api
  api:
    build:
      context: ./.docker/api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app:cached
    tty: true
    environment:
      - APP_ENV=development
    depends_on:
      - db
  db:
    build:
      context: ./.docker/db
      dockerfile: Dockerfile
    platform: linux/amd64 # M1チップの場合はコメントアウトを外す
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - type: bind
        source: ./.docker/db/my.cnf
        target: /etc/mysql/conf.d/my.cnf
      - db-volume:/var/lib/mysql:cached

volumes:
  db-volume: